# Generated by Django 2.0.13 on 2019-06-24 17:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default=datetime.datetime(2019, 6, 24, 17, 5, 52, 361178, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
    ]
