# Generated by Django 2.0.13 on 2019-06-13 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reader',
            name='everyone',
        ),
        migrations.RemoveField(
            model_name='reader',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='reader',
            name='student',
        ),
        migrations.AddField(
            model_name='reader',
            name='name',
            field=models.CharField(choices=[('students', 'pending'), ('staff', 'success'), ('everyone', 'cancelled')], default='everyone', max_length=200),
        ),
    ]
