# Generated by Django 2.0.13 on 2019-06-24 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20190613_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='content',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='reader',
            name='name',
            field=models.CharField(choices=[('students', 'students only'), ('staff', 'staff only'), ('everyone', 'everyone')], default='everyone', max_length=200),
        ),
    ]
