# Generated by Django 2.0.13 on 2019-07-01 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialstatement',
            name='credit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='financialstatement',
            name='debit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6),
        ),
    ]
