# Generated by Django 2.0.13 on 2019-07-04 14:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0003_auto_20190701_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialstatement',
            name='credit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='financialstatement',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 7, 4, 14, 45, 12, 572446, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='financialstatement',
            name='debit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
