# Generated by Django 2.2.6 on 2019-10-21 04:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('laptopreg', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='laptopsregister',
            old_name='laptopname',
            new_name='barcode',
        ),
        migrations.AddField(
            model_name='laptopsregister',
            name='macaddress',
            field=models.CharField(default=datetime.datetime(2019, 10, 21, 4, 41, 45, 489161, tzinfo=utc), max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laptopsregister',
            name='make',
            field=models.CharField(default=datetime.datetime(2019, 10, 21, 4, 41, 59, 41099, tzinfo=utc), max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laptopsregister',
            name='model',
            field=models.CharField(default=datetime.datetime(2019, 10, 21, 4, 42, 11, 478, tzinfo=utc), max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laptopsregister',
            name='ownership',
            field=models.CharField(default=datetime.datetime(2019, 10, 21, 4, 42, 20, 631916, tzinfo=utc), max_length=200),
            preserve_default=False,
        ),
    ]
