# Generated by Django 2.0.13 on 2019-06-24 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ResidenceHalls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rezhall',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True),
        ),
        migrations.AlterField(
            model_name='rezhall',
            name='lng',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True),
        ),
    ]
