# Generated by Django 2.0.13 on 2019-06-24 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ResidenceHalls', '0002_auto_20190624_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rezhall',
            name='location',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='rezhall',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
