# Generated by Django 2.0.13 on 2019-07-04 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guest',
            old_name='email',
            new_name='name',
        ),
    ]
