# Generated by Django 2.0.13 on 2019-07-05 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambulance', '0002_auto_20190613_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambulancerequests',
            name='status',
            field=models.CharField(default='pending', max_length=200),
        ),
    ]
